export const LOAD_MEMBER_LIST = 'LOAD_MEMBER_LIST';
export const ADD_NEW_MEMBER = 'ADD_NEW_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';

export const SET_MEMBER_LIST_LOCAL = 'SET_MEMBER_LIST_LOCAL';
export const ADD_MEMBER_LOCAL     = 'ADD_MEMBER_LOCAL';
export const UPDATE_MEMBER_LOCAL = 'UPDATE_MEMBER_LOCAL';
export const DELETE_MEMBER_LOCAL = 'DELETE_MEMBER_LOCAL';


export const LOAD_MEETING_LIST = 'LOAD_MEETING_LIST';
export const ADD_NEW_MEETING = 'ADD_NEW_MEETING';
export const UPDATE_MEETING = 'UPDATE_MEETING';
export const DELETE_MEETING = 'DELETE_MEETING';

export const SET_MEETING_LIST_LOCAL = 'SET_MEETING_LIST_LOCAL';
export const ADD_MEETING_LOCAL     = 'ADD_MEETING_LOCAL';
export const UPDATE_MEETING_LOCAL = 'UPDATE_MEETING_LOCAL';
export const DELETE_MEETING_LOCAL = 'DELETE_MEETING_LOCAL';
